vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatars:
            uri_prefix: /uploads/avatars
            upload_destination: "%kernel.project_dir%/public/uploads/avatars"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        videos:
            uri_prefix: /uploads/videos
            upload_destination: "%kernel.project_dir%/public/uploads/videos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
